# Generated by Django 2.2.4 on 2019-08-07 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='num_logradouro', default='', verbose_name='Address Number')),
                ('address', models.CharField(db_column='logradouro', default='', max_length=40, verbose_name='Address')),
                ('neighborhood', models.CharField(db_column='bairro', default='', max_length=15, verbose_name='Neighborhood')),
                ('city', models.CharField(db_column='cidade', default='', max_length=15, verbose_name='City')),
                ('uf', models.CharField(db_column='uf', default='', max_length=2, verbose_name='UF')),
                ('cep', models.CharField(db_column='cep', default='', max_length=8, verbose_name='CEP')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(db_column='nome_cartao', max_length=50, verbose_name='card_holder')),
                ('card_number', models.CharField(db_column='num_cartao', max_length=16, verbose_name='card_number')),
                ('month', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], db_column='mes_exp', verbose_name='Month')),
                ('year', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], db_column='ano_exp', verbose_name='Year')),
                ('is_active', models.BooleanField(db_column='ativo', default=False, verbose_name='Active')),
                ('client_id', models.ForeignKey(blank=True, db_column='cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='expirationDateApp.Client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'cartoes',
            },
        ),
    ]
