# Generated by Django 2.2.4 on 2019-08-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expirationDateApp', '0003_auto_20190807_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(db_column='num_cartao', max_length=16, verbose_name='card_number'),
        ),
    ]
